### ISSUE TITLE
Works in Chrome, doesn't load in Safari

### ISSUE THREAD

**Issue by ohld** [slacknation/medium#10]
So works and loads fine in Chrome, but is Safari like this: 

![2017-06-21 11 24 16](https://user-images.githubusercontent.com/5613295/27374400-48275b0e-5674-11e7-95f6-8709a5e3be51.png)

**Comment by slacknation** [comment]
are there any errors in dev console?

**Comment by ohld** [comment]
No, In Safari dev console nothing happening. But timeline shows: 
![2017-06-21 12 24 10](https://user-images.githubusercontent.com/5613295/27377099-ae9095e2-567c-11e7-8c03-b9c0e4c2435d.png)

**Comment by slacknation** [comment]
working now? looks like cause of old web3 library

**Comment by ohld** [comment]
Yeah! Thanks a lot.

**Comment by slacknation** [comment]
fixed with f1063206edc3b614ca01ed4788680f0e0e0917b4
