### ISSUE TITLE
Clarification on refund may be needed

### ISSUE THREAD

**Issue by majamee** [slacknation/medium#4]
On the page 11.html is written "refund rate: 1 eth to 100 dao tokens". As far as I understand it the refund should enable dao token holders to exchange their daos to eth. Shouldn't it therefore rather state "refund rate: 1 eth per 100 dao tokens"?

Best regards

**Comment by slacknation** [comment]
haha, i guess 100 dao tokens to 1 eth or 1 eth per 100 dao tokens is more accurate then.  b2ee53d86890c2a6b56ee8e5861f4f456b5afe70
