### ISSUE TITLE
Where do you pull your hashrate data from?

### ISSUE THREAD

**Issue by gcmartinelli** [slacknation/medium#5]

**Comment by slacknation** [comment]
https://github.com/slacknation/medium/blob/gh-pages/13/13.html#L118

**Comment by gcmartinelli** [comment]
Yes, I saw that in the homepage. But for hashrate from fork.ethstats.net we get only the realtime data. Are you scraping the site and logging the hashrate or is there a hidden API you are using?
thank you

**Comment by slacknation** [comment]
http://fork.ethstats.net/blocks

i store 'latest' in my database
