### ISSUE TITLE
Could you update /2 ?

### ISSUE THREAD

**Issue by 4fryn** [slacknation/medium#9]
Could you update /2 ? And also, could you share how you fetch the underlying data?

**Comment by slacknation** [comment]
updated https://medium.com/hacker-daily/25-1-of-presale-ether-accounts-never-accessed-before-6ea7dc0d7a80

rough steps
* get list of accounts by looking at block 0 
* get first block of each day
* check txcount for each account
* if txcount > 0, find the date of the first transaction

**Comment by 4fryn** [comment]
Thanks!
